# Generated by Django 5.1.1 on 2026-07-07 07:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.CharField(db_index=True, max_length=80)),
                ('tenant_id', models.CharField(db_index=True, max_length=80)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('updated_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('recommendation', models.TextField()),
                ('related_action', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(default='generated', max_length=30)),
                ('feedback', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.CharField(db_index=True, max_length=80)),
                ('tenant_id', models.CharField(db_index=True, max_length=80)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('updated_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('event_type', models.CharField(default='reminder', max_length=60)),
                ('starts_at', models.DateTimeField()),
                ('reminder_enabled', models.BooleanField(default=False)),
                ('notification_intent_id', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.CharField(db_index=True, max_length=80)),
                ('tenant_id', models.CharField(db_index=True, max_length=80)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('updated_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('metric', models.CharField(blank=True, max_length=80)),
                ('target_value', models.CharField(blank=True, max_length=80)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoadmapStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('definition', models.TextField()),
                ('xp_required', models.PositiveIntegerField(default=0)),
                ('is_future', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ScoreSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.CharField(db_index=True, max_length=80)),
                ('tenant_id', models.CharField(db_index=True, max_length=80)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('updated_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('overall_score', models.PositiveIntegerField(default=0)),
                ('dimensions', models.JSONField(default=dict)),
                ('explanation', models.JSONField(default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.CharField(db_index=True, max_length=80)),
                ('tenant_id', models.CharField(db_index=True, max_length=80)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('updated_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField()),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('unlocked_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('organization_id', 'tenant_id', 'key')},
            },
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.CharField(db_index=True, max_length=80)),
                ('tenant_id', models.CharField(db_index=True, max_length=80)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('updated_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(max_length=180)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('business_stage', models.CharField(default='Start', max_length=80)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('website_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('organization_id', 'tenant_id')},
            },
        ),
        migrations.CreateModel(
            name='IntegrationStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.CharField(db_index=True, max_length=80)),
                ('tenant_id', models.CharField(db_index=True, max_length=80)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('updated_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.CharField(max_length=60)),
                ('status', models.CharField(default='unknown', max_length=30)),
                ('last_checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'unique_together': {('organization_id', 'tenant_id', 'service')},
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=180)),
                ('category', models.CharField(max_length=80)),
                ('requirement_type', models.CharField(choices=[('manual_checklist', 'Manual checklist'), ('file_evidence', 'File evidence'), ('website_status', 'Website status'), ('accounting_fact', 'Accounting fact'), ('profile_field', 'Profile field'), ('ai_review', 'AI review'), ('admin_verification', 'Admin verification')], max_length=40)),
                ('xp_reward', models.PositiveIntegerField(default=10)),
                ('score_dimension', models.CharField(blank=True, max_length=80)),
                ('is_premium', models.BooleanField(default=False)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='business_hub.roadmapstage')),
            ],
            options={
                'ordering': ['stage__order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VaultDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.CharField(db_index=True, max_length=80)),
                ('tenant_id', models.CharField(db_index=True, max_length=80)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('updated_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('document_type', models.CharField(choices=[('nib', 'NIB'), ('npwp', 'NPWP'), ('sop', 'SOP'), ('template', 'Template'), ('finance', 'Finance'), ('legal', 'Legal'), ('other', 'Other')], default='other', max_length=40)),
                ('file_id', models.CharField(max_length=120)),
                ('source', models.CharField(default='file_manager', max_length=80)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('linked_checklist_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business_hub.checklistitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.CharField(db_index=True, max_length=80)),
                ('tenant_id', models.CharField(db_index=True, max_length=80)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('updated_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(max_length=80)),
                ('source_id', models.CharField(max_length=120)),
                ('amount', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=180)),
            ],
            options={
                'unique_together': {('organization_id', 'tenant_id', 'source_type', 'source_id')},
            },
        ),
        migrations.CreateModel(
            name='ChecklistCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.CharField(db_index=True, max_length=80)),
                ('tenant_id', models.CharField(db_index=True, max_length=80)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('updated_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('evidence_file_id', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='business_hub.checklistitem')),
            ],
            options={
                'unique_together': {('organization_id', 'tenant_id', 'item')},
            },
        ),
    ]
