# Generated by Django 5.1.1 on 2026-07-15 04:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('asset_type', models.CharField(choices=[('sop', 'SOP'), ('template', 'Template')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('file_id', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(default='business_hub', max_length=80)),
                ('is_premium', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['asset_type', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HubSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.CharField(db_index=True, max_length=80)),
                ('tenant_id', models.CharField(db_index=True, max_length=80)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('updated_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('weekly_digest_enabled', models.BooleanField(default=True)),
                ('ai_auto_insights_enabled', models.BooleanField(default=False)),
                ('default_goal_reminder_days', models.PositiveIntegerField(default=3)),
                ('preferences', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'unique_together': {('organization_id', 'tenant_id')},
            },
        ),
    ]
